### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jaydeepp095** [slim-python/pinterest-video-downloader-free-api#2]
It's Show Application Error

**Comment by slim-python** [comment]
Yes, lots of people have started using this api, and because of that my monthly limit is exceeding quickly(I'm using free version of heroku), wait for this month to end and it will start working again 😸

![Screenshot_20210228-085757748](https://user-images.githubusercontent.com/55599278/109406962-3aea5d00-79a3-11eb-9159-4abe6dce448e.jpg)

**Comment by jaydeepp095** [comment]
Thanks Slim-Python/Pinterest-Video-Downloader-Free-Api

But Now Develop Code For video and gif downloader for Pinterest Unlimited
and free.

But only Android mobile Application.
